baseURL = "https://bigdigital.co.uk/"
languageCode = "en-us"
title = "Big Digital"
theme = "hugo-lodi-theme-master"
googleAnalytics = "UA-XXXXXXXX-Y"

[params]
    theme_color = "#9c2322"
    description = "Portfolio of Lisa McGarry, Social Media Consultant"
    description_photo = "portfolio.jpg"
    favicon = "favicon.png"
    logo = "logo.png"
    email = "mcgarrylisa@gmail.com"
    # facebook = "lex.collado"
    twitter = "lisamcgarrylive"
    linkedin = "https://www.linkedin.com/in/lisamcgarrybelfast/"


[params.nav]
    enable = true

[params.hero]
    enable = true
    avatar = "Big-Digital-logo.jpg"
    subtitle = "A results driven Web Design & Digital Marketing Agency."
    hero_right = ["**Welcome to Big Digital, a web design and digital marketing agency based in Belfast, Northern Ireland, with clients in Antrim, Lisburn, Mid-Ulster and beyond.**", "You have a fantastic business. You have a website (if you don’t we can help with that too!), you’re on social media, so why aren’t people hearing about you and why aren’t you getting results?.", "We work with SMEs, Charities and Public Sector organisations to fine tune their digital strategy, to improve their online and social media presence and to perfect their SEO.", "Our digital experts will deliver business-changing results for clients, while also sharing our knowledge through events and training.", "Get in touch to see how we can take you to the next level."]
    resume = "ResumeCollado.pdf"

[params.process]
    enable = true
    title = "Our Services"
    subtitle = "We offer a full digital marketing service - from optimising your site for Google to handling your social media and web content strategy"

[params.case_studies]
    enable = false
    title = "Case Studies"
    subtitle = "Selected Works"

[params.Contact]
    enable = true
    title = "Contact Us"
    subtitle = "Drop us a line about your social media or website requirements and we'll get right back to you!"

[params.footer]
    enable = true
